name: 'Nightly Merge'

on:
  push:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Attempt merge
      run: |
        git fetch origin main
        git fetch origin feature/identity
        git merge origin/main
        git fetch origin feature/identity
        git checkout --ours CHANGELOG.md
        git add CHANGELOG.md  
        git commit -s -m "Nightly merge from 'origin/main' to 'feature/identity'"
        git push origin HEAD:feature/identity
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
