name: 'Nightly Merge'

on:
  push:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: robotology/gh-action-nightly-merge@v1.3.3
      with:
        stable_branch: 'main'
        development_branch: 'feature/identity'
        allow_ff: false
        allow_forks: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
