name: Increment Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'the tag'
        required: true
        type: string
  push:
    tags:
      - '*.*.*'

permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Tag and Version Information
        run: |
          TAG=${{ github.event.inputs.tag }}
          CURRENT_VERSION_ARRAY=($(echo "$TAG" | tr . '\n'))
          BASE=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:2}")
          BASE_X=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:1}.x")
          CURRENT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          CURRENT_VERSION_UNDERSCORE=$(IFS=_ ; echo "V_${CURRENT_VERSION_ARRAY[*]:0:3}")
          CURRENT_VERSION_ARRAY[2]=$((CURRENT_VERSION_ARRAY[2]+1))
          NEXT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          NEXT_VERSION_UNDERSCORE=$(IFS=_ ; echo "V_${CURRENT_VERSION_ARRAY[*]:0:3}")
          NEXT_VERSION_ID=$(IFS=0 ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}99")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "BASE_X=$BASE_X" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION_UNDERSCORE=$CURRENT_VERSION_UNDERSCORE" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION_UNDERSCORE=$NEXT_VERSION_UNDERSCORE" >> $GITHUB_ENV
          echo "NEXT_VERSION_ID=$NEXT_VERSION_ID" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE }}

      - name: Increment Patch Version
        uses: peternied/opensearch-core-version-updater@main
        with:
          previous-version: env.CURRENT_VERSION
          new-version: env.NEXT_VERSION
          update-current: true

      - run: git diff
      - run: git checkout .

      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_X }}

      - name: Increment Patch Version
        uses: peternied/opensearch-core-version-updater@main
        with:
          previous-version: env.CURRENT_VERSION
          new-version: env.NEXT_VERSION
          update-current: false

      - run: git diff
      - run: git checkout .

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Increment Patch Version
        uses: peternied/opensearch-core-version-updater@main
        with:
          previous-version: env.CURRENT_VERSION
          new-version: env.NEXT_VERSION
          update-current: false

      - run: git diff
      - run: git checkout .
